### ISSUE TITLE
CSS Conflicts

### ISSUE THREAD

**Issue by makinde** [philfung/add-to-homescreen#1]
I'm using bootstrap as my CSS framework. That framework defines a css class called `.modal`. That causes the `add-to-homescreen` modal to be stretched out since it also uses the `.modal` classname. You probably want to have webpack (or something else) add a namespace/prefix to all of the classnames used, or have your css rules only apply within the top level div made by the library.
<img width="390" alt="Screenshot 2023-09-14 at 10 39 12 AM" src="https://github.com/philfung/add-to-homescreen/assets/157415/e9f37521-bdab-4bed-9efb-1836dbd0402c">

**Comment by philfung** [comment]
hi @makinde , sorry for delay, i didnt see this issue until yesterday.  ive renamespaced all the css and made a new release 1.1 to fix this.

Please reference the latest release with the fix (ie using jsdelivr with tag 1.1 as shown [here](https://github.com/philfung/add-to-homescreen#usage-if-youre-not-making-changes-to-library))
