### ISSUE TITLE
add-to-homescreen not page specific 

### ISSUE THREAD

**Issue by JPMulder** [philfung/add-to-homescreen#12]
Hi, 
Works very well as intended
but I have noticed that your add-to-homescreen seems to be domain specific and not page specific 
I set it to run only 2 times when user land on the page. 
However, Once it has ran twice, your add-to-homescreen does not run again on another page i also need it to run on.
I want add-to-homescreen to be able to run two time on all pages I select it to run it on
Is there a way to achieve this. 
Thanks

**Comment by philfung** [comment]
hi @JPMulder , yes you can do this with the following change:

--- a/src/index.ts
+++ b/src/index.ts
@@ -797,7 +797,7 @@ class AddToHomeScreen {
   }
 
   _getModalDisplayCountKey(): string {
-    return 'adhs-modal-display-count';
+    return 'adhs-modal-display-count-' + window.location.pathname;
   }
