### ISSUE TITLE
Chrome Desktop Supports PWA installation banners

### ISSUE THREAD

**Issue by Jerome-lara** [philfung/add-to-homescreen#13]
addEventListener 'beforeinstallprompt'
deferredPrompt
Support in desktop chrome

**Comment by Jerome-lara** [comment]
In desktop chrome, you can monitor the installation button, and the user clicks the button to display the chrome installation UI.

**Comment by philfung** [comment]
this is implemented in [v2.0](https://github.com/philfung/add-to-homescreen/releases/tag/2.0)
