### ISSUE TITLE
how to close guides？How to not display the guidance process for the second time？

### ISSUE THREAD

**Issue by FairyWorld** [philfung/add-to-homescreen#2]
how to close guides？How to not display the guidance process for the second time？

**Comment by philfung** [comment]
hi @FairyWorld .

> how to close guides

1. Set flag _allowUserToCloseModal_ to _true_.  
2. The user can then click outside of the modal (ie in the black region) to close the modal.

Please note that (from experience), allowing the user to close the modal will decrease the home screen installation rate.

> How to not display the guidance process for the second time？

Ive just added a new flag _maxModalDisplayCount_ .  you can set this to _1_ to show the modal at most once, _2_ to show the modal at most 2 times, etc
Note again that this will decrease the home screen installation rate.

Thank you.
