### ISSUE TITLE
Button is not translated

### ISSUE THREAD

**Issue by redeye86** [philfung/add-to-homescreen#21]
The file ios-add-to-home-screen-button.svg is a graphic that contains both the icon and the text "Add to homescreen". Therefore the text is not part of the localization. I think the the text should be removed from the svg and the icon should be used alone with a localized text.

**Comment by philfung** [comment]
all the text is implemented programatically in [v2.0](https://github.com/philfung/add-to-homescreen/releases/tag/2.0).  All buttons have been translated.
