### ISSUE TITLE
Doesn’t work on iPad, displays “install on mobile device”

### ISSUE THREAD

**Issue by WarpedPixel** [philfung/add-to-homescreen#22]
If you configure iPad to request mobile site (which is not default), it will display installation instructions but they are incorrect (location of share button is top right, not bottom). 

This should work like iPhone regardless of safari configuration.

**Comment by philfung** [comment]
i'm working on a rewrite for desktop browsers which will fix this.

**Comment by philfung** [comment]
thanks so much for reporting
