### ISSUE TITLE
Adding 'ru' locale

### ISSUE THREAD

**Issue by alexander-potemkin** [philfung/add-to-homescreen#25]
Hey and thank you for you for the product! Would you be open to merge a pull request with 'ru' locale?

**Comment by philfung** [comment]
Yes please do!  Note I am in midst of or big rewrite and enhancement to enable desktop apps so you may need to send another pull in a few weeks

**Comment by philfung** [comment]
hi @alexander-potemkin , i added a [basic RU locale file](https://github.com/philfung/add-to-homescreen/commit/5b74ccc0a612256f86ecc12930aad4737d803bc6#diff-3bfd0b589cbcd056d7930cbb5e35129836419f515a9ec5efe82fedb426266a37) (using AI), would you mind fixing it for any inaccuracies?   Thank you!!

**Comment by claudiobosticco** [comment]
Hi @philfung, if you add the 'it' locale, I'll be glad to check it for inaccuracies, thank you in advance

**Comment by philfung** [comment]
@claudiobosticco great thanks.  [here](https://github.com/philfung/add-to-homescreen/commit/d73919fd57f4e9dcf40a0ccf4d9c059dfa166a89) you go.  Please send pull request if any issues.  Also appreciate a star on the github!

**Comment by claudiobosticco** [comment]
thank you very much @philfung! The translations seem spot on to me!

**Comment by alexander-potemkin** [comment]
> hi @alexander-potemkin , i added a [basic RU locale file](https://github.com/philfung/add-to-homescreen/commit/5b74ccc0a612256f86ecc12930aad4737d803bc6#diff-3bfd0b589cbcd056d7930cbb5e35129836419f515a9ec5efe82fedb426266a37) (using AI), would you mind fixing it for any inaccuracies? Thank you!!

Apologies for the delay! And thank you! Looks good to me! :)

Just curious - what is the tool / prompt you used for that?

**Comment by philfung** [comment]
@alexander-potemkin used Claude
