### ISSUE TITLE
Issue with using button to launch AddToHomeScreenInstance

### ISSUE THREAD

**Issue by sunstarjeff** [philfung/add-to-homescreen#26]
I used your code sample to try to use a BUTTON tag to launch the AddToHomeScreenInstance, but no matter what I try, when I click on the button, the function launches the modal creates the the DIV ("adhs-container"), but then immediately closes/removes the DIV.

`<script>
  document.getElementById('addToHomeScreen').addEventListener('click', function () {
  window.AddToHomeScreenInstance = new window.AddToHomeScreen({
  appName: 'App Name',
  appIconUrl: '/mobile/iOS.png',
  assetUrl: '/_scripts/add-to-homescreen-1.9/assets/img/',
  allowUserToCloseModal: true,
  maxModalDisplayCount: -1
  });
  ret = window.AddToHomeScreenInstance.show('en');
  });
</script>`

If you'd like I could provide an example video or URL.

Do you happen to have a working sample?

**Comment by philfung** [comment]
hi @sunstarjeff i got it to work, i think you were missing an event.stopPropagation() in your click handler

Code: https://gist.github.com/philfung/f4b152aa3c57f29bc5b180a16562548a

Screenshot: 
<img width="334" alt="Screenshot 2024-08-19 at 11 14 17 PM" src="https://github.com/user-attachments/assets/4baea972-0713-4b0a-99d8-11369c701517">
<img width="321" alt="Screenshot 2024-08-19 at 11 14 32 PM" src="https://github.com/user-attachments/assets/54fa81ab-1525-447a-82fa-b450ea071e50">

**Comment by sunstarjeff** [comment]
Thank you for your help!

**Comment by philfung** [comment]
np!  thanks for trying out the framework - appreciate if you can give the repo a star.
