### ISSUE TITLE
Can't get the overlay to appear on click 

### ISSUE THREAD

**Issue by NilsDannemann** [philfung/add-to-homescreen#29]
I can get it to work as in your demo page (overlay shows up after load).

But I need it to appear on click.
I'm getting a strange error, where the overlay vanishes again immediately after click.

Is this a known issue?

**Video of the issue:**
https://github.com/user-attachments/assets/3cda718b-4547-4b35-8b87-9187a83fd3e4

**Site for testing:**
[https://66dccab93975a80008b04ebd--little-dayplanner.netlify.app/](https://66dccab93975a80008b04ebd--little-dayplanner.netlify.app/)

**Comment by philfung** [comment]
Hello!  Someone else had this same issue.  They were missing an event.stoppropogation() in the click handler.  Can you try that?  If doesn't work will try to debug

Example

https://gist.github.com/philfung/f4b152aa3c57f29bc5b180a16562548a

Thanks!

**Comment by NilsDannemann** [comment]
Oh my god, yeah that works. 
Thank you so much man!

**Comment by philfung** [comment]
Thanks for trying the library Nils!  Appreciate it you can give the repo a
"star".

**Comment by NilsDannemann** [comment]
Will do 👍
