### ISSUE TITLE
Uncaught SyntaxError: expected expression, got '<'

### ISSUE THREAD

**Issue by dopinder100** [philfung/add-to-homescreen#30]
I used the copy in the "dist" folder and I get the following error:

Uncaught SyntaxError: expected expression, got '<'

**Comment by philfung** [comment]
hello - i can't seem to repro your issue.  please see https://philfung.github.io/ which is using the exact "dist" folder.  can you provide repro?

**Comment by dopinder100** [comment]
I am sorry, it is totally a mistake on my side. Somehow the js file didn't load properly on a first attempt, and it was cached. So, subsequently, even after I have replaced the js file, the same error persists, because the correct js file was never get loaded.
