### ISSUE TITLE
Add to Home Screen - cs translation

### ISSUE THREAD

**Issue by miroslavhajek** [philfung/add-to-homescreen#37]
### Expected
Now is `Add to Home Screen` in iOS translated as `Přidat na plochu`.

![IMG_2649](https://github.com/user-attachments/assets/edfe720e-e0e8-4557-80b7-e1bb5ad25edc)

### Actual
`Add to Home Screen` - `Přidat na domovskou obrazovku`.

### Location

https://github.com/philfung/add-to-homescreen/blob/main/src/locales/cs.json#L2C4-L2C22

**Comment by philfung** [comment]
Thank you!  Please open a pull request and I can merge

**Comment by miroslavhajek** [comment]
FIXED in https://github.com/philfung/add-to-homescreen/pull/38
