### ISSUE TITLE
Modal still appearing on desktop with showErrorMessageForUnsupportedBrowsers set to false

### ISSUE THREAD

**Issue by dankingsley** [philfung/add-to-homescreen#4]
Hi,

On both Chrome and Safari on a Mac, when I set showErrorMessageForUnsupportedBrowsers to false, the black background which would show up behind the modal window still appears. The modal and message itself isn't there, just a blank background. Is this a known issue?

**Comment by philfung** [comment]
hi, let me try to repro this

**Comment by philfung** [comment]
hi @dankingsley , this has been fixed in https://github.com/philfung/add-to-homescreen/commit/2e7119d3a47f14468a15e95043bb37fbac2bb8f7 .  Use the latest release 1.6 .  Thanks for reporting!
