### ISSUE TITLE
Icon doesn't appear for android chrome add to homescreen. 

### ISSUE THREAD

**Issue by Shahir-Abdullah** [philfung/add-to-homescreen#43]
This library is working perfectly for iphone. When i go to my website it's showing the pop up messages and it's adding it to the homescreen with the desired logo of my website. 

However while trying to do the same from android chrome, it's not using the provided logo.

**Comment by philfung** [comment]
Hi Shahir, thanks for the report.  Can you show me how to reproduce your issue?  I'm loading in Android Chrome and it seems to show the correct logo.

<img width="315" alt="Screenshot 2024-10-09 at 1 41 01 PM" src="https://github.com/user-attachments/assets/d922a455-ad91-4a83-8d2e-f6a35865b0c5">

**Comment by Shahir-Abdullah** [comment]
Hi Philip, actually it’s not when the window loads. The logo is appearing
perfectly in the pop up. i’m talking about when the shortcut is created in
the home screen, the icon for that shortcut is not working for android. i
have attached the screenshot for both iphone and android for you to see.

Thank you

**Comment by Shahir-Abdullah** [comment]
Hi Philip, actually it’s not when the window loads. The logo is appearing
perfectly in the pop up. i’m talking about when the shortcut is created in
the home screen, the icon for that shortcut is not working for android. i
have attached the screenshot for both iphone and android for you to see.

Thank you
![IMG_0361](https://github.com/user-attachments/assets/6e46ae67-8823-4c06-a57f-32a14cb74b70)
![IMG_0362](https://github.com/user-attachments/assets/8e3db572-c1ef-488b-99e3-79711cd7a7b2)
![Screenshot_20241010_164230_Chrome](https://github.com/user-attachments/assets/7dafc473-d1d3-44a4-af36-c4df8a8e3b58)
![Screenshot_20241010_164250_One UI Home](https://github.com/user-attachments/assets/3f2330ca-f403-4fd9-947e-9e5b8c5b4773)

**Comment by Shahir-Abdullah** [comment]
Hi Claudiobosticco, thank you for the tip, i had the manifest.json but it was configured incorrectly. I have corrected it and now it's working !
