### ISSUE TITLE
adhs-container z-index not high enough

### ISSUE THREAD

**Issue by claudiobosticco** [philfung/add-to-homescreen#46]
Hello, I just realized that with the js framework I'm using to create my web pages (SmartClient by Isomorphic) I have to augment the z-index to 999999 (99999 wasn't enough). Maybe is something which could be modified in the library or or could it cause problems?

**Comment by philfung** [comment]
Will take a look at your issues today

**Comment by philfung** [comment]
[fixed](https://github.com/philfung/add-to-homescreen/commit/5606262386d4aa13af8c8cad23d38a6df53b66a6) and included in new [release](https://cdn.jsdelivr.net/gh/philfung/add-to-homescreen@2.3)

**Comment by philfung** [comment]
appreciate if you can give the repo a star as well!
