### ISSUE TITLE
Support for the Thai language.

### ISSUE THREAD

**Issue by stefanvucic** [philfung/add-to-homescreen#47]
We have implemented this library in our product and it works well only thing we are missing is the Thai language support. Is it possible to add this in the future?

**Comment by philfung** [comment]
hi @stefanvucic , added in https://github.com/philfung/add-to-homescreen/commit/57ecd1ce539179f294cf69ac71d6c8a2a23e6028 .  
Can you please:
1. check that the Thai language is correct (i just used GPT to do this) and send a pull request with correction if needed?
2. appreciate if you can give the repo a star!!

**Comment by philfung** [comment]
<img width="545" alt="Screenshot 2024-10-29 at 11 35 28 AM" src="https://github.com/user-attachments/assets/8fa772ff-b5c4-4441-8f94-0dac6149af06">
<img width="548" alt="Screenshot 2024-10-29 at 11 35 03 AM" src="https://github.com/user-attachments/assets/c59215b1-e7bd-4291-8428-08fb45c03c2c">

**Comment by stefanvucic** [comment]
That should be it. Thanks for the quick response.

**Comment by stefanvucic** [comment]
The translation looks fine. Thanks for the quick response.

I tried to test it but looks like Thai is not available in version 2.3 and version 2.4 is not available yet. Can you please let me know when the new version with the Thai language is available?

**Comment by philfung** [comment]
hello @stefanvucic 2.4 w/thai is now available.  sorry for delay

https://cdn.jsdelivr.net/gh/philfung/add-to-homescreen@2.4/dist/add-to-homescreen.min.js
https://cdn.jsdelivr.net/gh/philfung/add-to-homescreen@2.4/dist/add-to-homescreen.min.css
