### ISSUE TITLE
The Modal POPUP dont disappear on click outside in desktop PC browsers

### ISSUE THREAD

**Issue by devmilitia** [philfung/add-to-homescreen#5]
Hi Partner
The Modal POPUP dont disappear on click outside in desktop PC browsers
allowUserToCloseModal: true,

Best Regards

**Comment by philfung** [comment]
thanks for report, fixed

https://github.com/philfung/add-to-homescreen/commit/863382ec72f8c375c22d5659e4e3e3ab779f6d87
