### ISSUE TITLE
Possibility to disable layer on desktop`?

### ISSUE THREAD

**Issue by VersionReview** [philfung/add-to-homescreen#53]
Hi,

is is possible to just show the layers with installation on mobile and NOT on desktop....sometimes you dont want to install the pwa on desktop...usecase: for und back buttons are really needed on desktop and therefore showing the desktop website is good enough...if the site is installed as pwa theses buttons would be missing (at least as far as i know)

**Comment by philfung** [comment]
Thanks for feedback will make change

**Comment by VersionReview** [comment]
ok this code should solve the problem (at least it did for me) - unfortunately i dont know how to make a pull request so here a detailled guide:

Detailed Steps
Step1:
Adding the showLayerOnDesktop Parameter:
Add the showLayerOnDesktop parameter to the parameter list of the AddToHomeScreen function.
Set the default value to true.

function AddToHomeScreen(options) {
    let { appIconUrl, appName, appNameDisplay, assetUrl, maxModalDisplayCount, showLayerOnDesktop } = options;
    let closeEventListener = null;
    const userAgent = window.navigator.userAgent;

    // Set the default value for showLayerOnDesktop to true
    showLayerOnDesktop = showLayerOnDesktop === undefined ? true : showLayerOnDesktop;

Step2:
Checking the showLayerOnDesktop Parameter:
Check the value of the showLayerOnDesktop parameter in the show method.
If showLayerOnDesktop is false, prevent the display of the layer on desktop systems.

else {
    debugMessage("DESKTOP");
    ret = new types_1.DeviceInfo((_isStandAlone = false), (_canBeStandAlone = false), (_device = _device));

    // Check if the layer should be shown on desktop
    if (showLayerOnDesktop) {
        if (isDesktopChrome() || isDesktopEdge()) {
            debugMessage("DESKTOP CHROME");
            _incrModalDisplayCount();
            showDesktopInstallPrompt();
        }
        else if (isDesktopSafari()) {
            debugMessage("DESKTOP SAFARI");
            _incrModalDisplayCount();
            _showDesktopSafariPrompt();
        }
    }
}

Example Usage of the New Parameter
If you want to use the showLayerOnDesktop parameter in your script, you can set it as follows:
<script>
document.addEventListener('DOMContentLoaded', function () {
 window.AddToHomeScreenInstance = window.AddToHomeScreen({
  appName: 'Aardvark',                                   // Name of the app.
                                                         // Required.
  appNameDisplay: 'standalone',                          // If set to 'standalone' (the default), the app name will be diplayed
                                                         // on it's own, beneath the "Install App" header. If set to 'inline', the
                                                         // app name will be displayed on a single line like "Install MyApp"
                                                         // Optional. Default 'standalone'
  appIconUrl: 'apple-touch-icon.png',                    // App icon link (square, at least 40 x 40 pixels).
                                                         // Required.
  assetUrl: 'https://cdn.jsdelivr.net/gh/philfung/add-to-homescreen@2.9/dist/assets/img/',  // Link to directory of library image assets.

  maxModalDisplayCount: -1,                               // If set, the modal will only show this many times.
                                                         // [Optional] Default: -1 (no limit).  (Debugging: Use this.clearModalDisplayCount() to reset the count)
showLayerOnDesktop: false   // Set to false to prevent the layer from showing on desktop systems
});

 ret = window.AddToHomeScreenInstance.show('en');        // show "add-to-homescreen" instructions to user, or do nothing if already added to homescreen
                                                         // [optional] language.  If left blank, then language is auto-decided from (1) URL param locale='..' (e.g. /?locale=es) (2) Browser language settings
});
</script>
</body>


Summary
Adding the showLayerOnDesktop Parameter:
Add the showLayerOnDesktop parameter to the parameter list of the AddToHomeScreen function.
Set the default value to true.
Checking the showLayerOnDesktop Parameter:
Check the value of the showLayerOnDesktop parameter in the show method.
If showLayerOnDesktop is false, prevent the display of the layer on desktop systems.
With these changes, you can control the display of the installation layer on desktop systems by setting the showLayerOnDesktop parameter accordingly.

**Comment by philfung** [comment]
@VersionReview thakns for feedback, added a displayOptions = {showMobile: true, showDesktop: false}  in           (https://github.com/philfung/add-to-homescreen/commit/c4f1b50777208f672e6563f99a94ad0e6d93b3e3)
