### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Alukard-X** [philfung/add-to-homescreen#55]
Does it works in this build?
window.AddToHomeScreenInstance.show('ru');
I'm trying to get it translated but it keeps as 'en'.
![image](https://github.com/user-attachments/assets/25d7d48d-78e7-4743-9dff-603cb49bf595)
![image](https://github.com/user-attachments/assets/bff1a18c-285c-4efe-89be-327a934c4d35)
![image](https://github.com/user-attachments/assets/8bd6b43a-f89f-4718-a76e-45b792f1b27d)

local override

**Comment by philfung** [comment]
@Alukard-X thanks for pointing this out.  this is fixed in [latest release](https://github.com/philfung/add-to-homescreen/releases/tag/2.7).  Please verify that it is fixed on your end.  Appreciate a star as well if helpful!

**Comment by Alukard-X** [comment]
![image](https://github.com/user-attachments/assets/0bd91ed9-c1a3-468c-b922-c73e125fd338)
p.s. I was altering all files today to make "custom" template to make same thing )
![image](https://github.com/user-attachments/assets/ddc47bd2-3632-413d-97b6-2293ecc52da9)
p.s.s. maybe it's possible to add similar code as mine to "put" default language of user's browser? (if it's empty)
![image](https://github.com/user-attachments/assets/775dcd67-87da-43ed-b4d9-07db4c32060d)
accept-language: ru-RU,ru;q=0.9

**Comment by Alukard-X** [comment]
p.s.
`   
     var get_url_params = function () {
            var params = {};
            window.location.href.split('#')[0].replace(/[?&]+([^=&]+)=([^&]*)/gi, function (m, key, value) {
                params[key] = value;
            });
            return params;
        };

        var get_url_param = function (name, default_value) {
            var params = get_url_params();
            if (default_value === undefined) {
                default_value = null;
            }
            return params[name] !== undefined ? params[name] : default_value;
        };

        var get_browser_locale = function () {
            if (navigator.languages !== undefined) {
                return navigator.languages[0];
            } else {
                return navigator.language;
            }
        };

        var get_browser_short_locale = function () {
            var locale = get_browser_locale();
            return locale.split("-")[0];
        };

        var get_available_locale = function (available_locales, default_locale, force_locale) {

            if (default_locale === undefined) {
                default_locale = available_locales[0];
            }

            if (force_locale !== undefined) {
                if (available_locales.indexOf(force_locale) !== -1) {
                    return force_locale;
                }
            }

            var locale = get_browser_locale();
            if (available_locales.indexOf(locale) !== -1) {
                return locale;
            }

            var shortLocale = get_browser_short_locale();
            if (available_locales.indexOf(shortLocale) !== -1) {
                return shortLocale;
            }
            var len = available_locales.length;
            for (var i = 0; i < len; i++) {
                if (available_locales[i].indexOf(shortLocale) !== -1) {
                    return available_locales[i];
                }
            }

            return default_locale;
        };
`

**Comment by philfung** [comment]
@Alukard-X yes, this is a great idea.
i've updated the code to check for a default browser setting/url param 
https://github.com/philfung/add-to-homescreen/commit/3deba55f770d0c01378f100ac33d1cffca84a25c
and updated the release.

**Comment by Alukard-X** [comment]
vi Vietnamese
(short code from language)

**Comment by Alukard-X** [comment]
![image](https://github.com/user-attachments/assets/39fb868b-fbda-469c-8924-27209771f1e8)
![image](https://github.com/user-attachments/assets/4e99522c-906d-4f21-ae87-f09290a70631)
![image](https://github.com/user-attachments/assets/66bf3c53-fbf3-4752-9fbd-3faeeac62385)

**Comment by Alukard-X** [comment]
BTW it seems that on Android  (chrome) it cannot "detect" is it installed already or not.... so popup will appear again and again even if it's installed.
