### ISSUE TITLE
Infinite loop for showDesktopInstallPrompt in Chrome Incognito mode

### ISSUE THREAD

**Issue by jithinvmohan** [philfung/add-to-homescreen#61]
`beforeinstallprompt` does not fire in Incognito mode and hence it is never registered in Chrome/Edge in Incognito mode. In that case `showDesktopInstallPrompt` gets called infinitely

**Comment by philfung** [comment]
thanks @jithinvmohan for report.  fixed in https://github.com/philfung/add-to-homescreen/commit/ff601e6dc1153f889167b40409eefb4495214956

appreicate a star for the repo!
