### ISSUE TITLE
In Chrome Browser instead of the text maybe show the user the steps to install PWA in Chrome ?

### ISSUE THREAD

**Issue by devmilitia** [philfung/add-to-homescreen#9]
In Chrome Browser instead of the text :
Please open this website on a mobile device.
Installing to your home screen is currently only supported on IOS and Android.

maybe show the user the steps to install PWA in Chrome ?
<img width="960" alt="screenshot_2024_02_20_at_07_49_42" src="https://github.com/philfung/add-to-homescreen/assets/152797216/774b4bc5-c1ff-4512-92d0-f6660971a324">
The webpage in chrome browsers offer to the users the option to install app in windows,
maybe place a modal with the steps to install the PWA in chrome browsers ?
<img width="960" alt="screenshot_2024_02_20_at_08_01_42" src="https://github.com/philfung/add-to-homescreen/assets/152797216/fe5a7f40-e076-4323-ba11-73a9346f2a92">

**Comment by philfung** [comment]
this is a good idea, let me take a look

**Comment by philfung** [comment]
![Screenshot from 2024-02-24 16-34-42](https://github.com/philfung/add-to-homescreen/assets/1054593/7dc6548c-14ab-45d4-9224-7a04a67a3227)
maybe something like this?

**Comment by philfung** [comment]
desktop chrome support implemented in [v2.0](https://github.com/philfung/add-to-homescreen/releases/tag/2.0)
